db:
  image: percona:latest
  restart: always
  volumes:
    - openxpki-percona:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
web:
  image: janknieling/openxpki:latest
  dns: 1.1.1.1
  hostname: pki.example.org
  restart: always
  ports:
    - "8080:80"
    - "8443:443"
  links:
    - db:mysql
  volumes:
    - openxpki-config:/etc/openxpki
    - openxpki-apache2-logs:/var/log/apache2
    - openxpki-logs:/var/log/openxpki
  environment:
    - APP_DB_NAME=openxpki
    - APP_DB_USER=openxpki
    - APP_DB_PASS=${DB_OPENXPKI_PASSWORD}
    - APP_DB_ROOT_PASS=${DB_ROOT_PASSWORD}
